### ISSUE TITLE
clone工程运行npm run dev，报错The provided value "./app/dist" is not an absolute path!

### ISSUE THREAD

**Issue by mijiawei** [djs66256/ExDebug#1]
尝试运行您的工程，出现问题，想知道是否是npm版本的关系？（npm version: 5.0.3）

执行 npm run dev

> Rose@1.0.0 dev /Users/micky/ExDebug
> webpack -w

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./app/dist" is not an absolute path!

**Comment by djs66256** [comment]
之前整理的时候有些遗漏的地方，现在应该可以运行了。
